#!/bin/bash
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "~~                                                          ~~"
echo "~~ Home Assistant - SmartThings HomeBridge Installer Script ~~"
echo "~~                                                          ~~"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run with sudo."
   echo "Please use: \"sudo ${0} ${*}\"" 1>&2
   exit 1
fi

echo
echo  "Please take a moment to setup your first MQTT user"

echo -n "~~~~~~~~~~~~~~~~~~~~~~< MQTT Username >~~~~~~~~~~~~~~~~~~~~~~~

	~ Choose a UserName for Mosquitto MQTT.
	~ You have 10 sec or a default username 'pi' will be use

Enter Username > "
read -t 10 -r mqtt_username
if [ ! "$mqtt_username" ]; then
  mqtt_username=pi
fi

echo
echo -n "~~~~~~~~~~~~~~~~~~~~~~< MQTT Password >~~~~~~~~~~~~~~~~~~~~~~~

	~ Choose a password for Mosquitto MQTT.
	~ You have 10 sec or a default password 'raspberry' will be use

Enter Password > "
read -t 10 -s mqtt_password
if [ ! "$mqtt_password" ]; then
  mqtt_password=raspberry
fi


echo
echo -n "~~~~~~~~~~~~~~~~~~~~~< MQTT Broker IP >~~~~~~~~~~~~~~~~~~~~~~~

	~ Enter the MQTT host IP.
	~ Examples: '192.168.x.x' or 'hassbian.local' or localhost
	~ You have 10 sec or a default address 'localhost' will be use

Enter Broker > "
read -t 10 -r mqtt_broker
if [ ! "$mqtt_broker" ]; then
  mqtt_broker=localhost
fi

echo
echo -n "~~~~~~~~~~~~~~~~~~~< Do You Want it all >~~~~~~~~~~~~~~~~~~~~~
	~ If you answer 'y', this will also install:
	~ Harmony API - better responce time to Harmony
	~ Samba - file sharing
	~ You have 10 sec or they will be installed
	~ Press 'n' to skip 
	
Install all? > "
read -t 10 -r install_all
if [ ! "$install_all" ]; then
  install_all=y
fi
if [[ "$install_all" == "y" ]]
then
  echo
  echo "Grate!"
  else
    echo
    echo "Harmony API and Samba will not be installed"
fi

echo
echo "Running apt-get preparation.."
echo "(this my take a while)"
echo
sudo apt-get update
sudo apt-get upgrade -y

echo
echo "Install Avahi (HomeKit Support)"
echo
sudo apt-get install -y libavahi-compat-libdnssd-dev

if [[ "$install_all" == "y" ]]
then
echo
echo "Insralling Samba.."
echo
sudo hassbian-config install samba
fi

echo
echo "Insralling Mosquitto.."
echo
echo "$mqtt_username $mqtt_password" | sudo hassbian-config install mosquitto

echo
echo "Initializing password file"
echo
sudo rm /etc/mosquitto/pwfile
cd /etc/mosquitto
touch pwfile
chown mosquitto:mosquitto pwfile
chmod 0600 pwfile

echo
echo "Creating password entry for user - $mqtt_username"
echo
mosquitto_passwd -b pwfile "$mqtt_username" "$mqtt_password"

echo
echo "Restarting Mosquitto service"
echo
systemctl restart mosquitto.service

cat >> /home/homeassistant/.homeassistant/configuration.yaml <<EOF

## MQTT server (pull devices from SmartThing's 'MQTT Bridge' smartapp)
mqtt:
  broker: $mqtt_broker
  port: 1883
  client_id: home-assistant-1
  username: $mqtt_username
  password: $mqtt_password
EOF

echo
echo "Installig node.js 7.x and npm.."
echo
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs

echo
echo "Installig SmartThings to MQTT bridge.."
echo "(Pull devices from SmartThing's 'MQTT Bridge' SmartApp)"
echo
sudo npm install -g smartthings-mqtt-bridge

echo
echo "Configuring smartthings-mqtt-bridge's config.yml.."
echo
cat >> /home/pi/config.yml <<EOF
---
mqtt:
    # Specify your MQTT Broker's hostname or IP address here
    host: mqtt://$mqtt_broker
    # Preface for the topics $PREFACE/$DEVICE_NAME/$PROPERTY
    preface: smartthings

    # Suffix for the state topics $PREFACE/$DEVICE_NAME/$PROPERTY/$STATE_SUFFIX
    # state_suffix: state
    # Suffix for the command topics $PREFACE/$DEVICE_NAME/$PROPERTY/$COMMAND_SUFFIX
    # command_suffix: cmd

    # Other optional settings from https://www.npmjs.com/package/mqtt#mqttclientstreambuilder-options
    username: $mqtt_username
    password: $mqtt_password

# Port number to listen on
port: 8080
EOF

echo
echo "Installing HomeBridge.."
echo "(HomeKit suppoot)"
echo
sudo npm install -g --unsafe-perm homebridge

echo
echo "Installing HomeBridge HomeAssistant support plugin.."
echo
sudo npm install -g homebridge-homeassistant

echo
echo "Configureing 'smartthings-mqtt-bridge' in HomeBridge.."
echo
cd /home/pi/.homebridge
touch config.json
cat >> /home/pi/.homebridge/config.json <<EOF
{
   "bridge":{
      "name":"Homebridge",
      "username":"CC:22:3D:E3:CE:30",
      "port":51826,
      "pin":"031-45-154"
   },
   "platforms":[
      {
         "platform":"HomeAssistant",
         "name":"HomeAssistant",
         "host":"http://localhost:8123",
         "password": "",
         "supported_types":[
            "binary_sensor",
            "climate",
            "cover",
            "device_tracker",
            "fan",
            "group",
            "input_boolean",
            "light",
            "lock",
            "media_player",
            "scene",
            "sensor",
            "switch"
         ],
         "logging":true
      }
   ]
}
EOF

if [[ "$install_all" == "y" ]]
then
echo
echo "Install Harmony API"
echo "Better server for speed up harmony devices responce"
echo
sudo npm install forever -g
git clone https://github.com/maddox/harmony-api.git harmony_api
cat >> /home/pi/harmony_api/config/config.json <<EOF
{
  "mqtt_host": "mqtt://$mqtt_broker",
  "mqtt_options": {
      "port": 1883,
      "username": "$mqtt_username",
      "password": "$mqtt_password",
      "rejectUnauthorized": false
  }
}
EOF
sudo harmony_api/script/bootstrap
fi

echo
echo "Install pm2"
echo
sudo npm install pm2 -g

echo
echo "Updete stuff for good practice"
echo
sudo apt-get update

echo
echo "Cofigure PM2 autostart on boot"
echo "for the services: smartthings-mqtt-bridge / homebridge / harmony-api"
echo
sudo pm2 start smartthings-mqtt-bridge
sudo pm2 start homebridge
sudo pm2 start harmony_api/app.js --name harmony-api
sudo pm2 ls
sudo pm2 save
sudo pm2 startup

echo
echo "Done."
echo
echo "Rebooting.."
sudo reboot
